COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//protocols/mesh/api:onos-protocols-mesh-api',
    '//apps/meshmanager:onos-apps-meshmanager'
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
