COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:COMPILE',
    '//lib:org.osgi.compendium',
    '//lib:org.apache.felix.scr.annotations',
    '//utils/misc:onlab-misc',
    '//core/common:onos-core-common',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Mesh Manager',
    category = 'Mesh Manager',
    url = 'http://onosproject.org',
    description = 'Mesh Manager',
)
